// Ability synergy with the new rules: every new effect key changes the game the way its text says.
require('./load.js'); const G = AU.G, MW = AU.MasteryWeb, WB = AU.Warbands, SY = AU.Synthesis, SO = AU.Society, U = AU.U;
function assert(c, m) { if (!c) throw new Error(m); }
function fresh(civ, leader, v2, seed) { return G.newGame({ playerCiv: civ, playerLeader: leader, mapSize: 'small', mapType: 'continents', numCivs: 3, numStates: 2, seed: seed || 9, difficulty: 'prince', v2: !!v2 }); }
function found(g, p) { return U.foundCity(g, G.civUnits(g, p.idx).filter(u => u.type === 'settler')[0]); }
// every rework applies to a real ability and its text mentions it
const SYN = AU.V2_SYNERGY; let n = 0;
for (const id in SYN.leader) { const a = AU.LEADER_BY_ID[id].ability; for (const k in SYN.leader[id].fx) assert(a.fx[k] !== undefined, id + ' lacks ' + k); n++; assert((SYN.leader[id].both && a.desc.indexOf(SYN.leader[id].both) >= 0) || (SYN.leader[id].v2 && a.descV2.indexOf(SYN.leader[id].v2) >= 0), id + ' text'); }
for (const id in SYN.civ) { const a = AU.CIV_BY_ID[id].ability; for (const k in SYN.civ[id].fx) assert(a.fx[k] !== undefined, id + ' lacks ' + k); n++; }
console.log('reworked abilities:', n);
// claims: America four free claims, China cheaper claims, Egypt Influence per river tile
{ const g = fresh('america', 'lincoln', true); const p = G.player(g), s = found(g, p); assert(G.freeClaims(g, s) === 4, 'America: four free claims'); while (G.claimedCount(g, s) < 4) G.claimTile(g, s, G.expansionCandidates(g, s)[0]); assert(G.claimBlocker(g, s) === 'building', 'fifth claim needs the Marker'); }
{ const g = fresh('china', 'qin', true); const p = G.player(g), s = found(g, p); while (G.claimedCount(g, s) < 3) G.claimTile(g, s, G.expansionCandidates(g, s)[0]); assert(G.claimCost(g, s) === Math.round(10 * 0.75), 'China: claims 25% cheaper (' + G.claimCost(g, s) + ')'); }
{ const g = fresh('egypt', 'cleopatra', true); const p = G.player(g), s = found(g, p); const c = G.expansionCandidates(g, s)[0]; g.tiles[c].river = true; p.influence = 0; s.pendingGrowth = 1; assert(G.expandTo(g, s, c), 'river claim'); assert(p.influence === 3, 'Egypt: +3 Influence per river tile (' + p.influence + ')'); }
// Command: Rome roads, Shawnee far discount, Persia +2
{ const g = fresh('rome', 'augustus', false); const p = G.player(g), s = found(g, p); const u = G.spawnUnit(g, p.idx, 'warrior', s.tile); const far = g.tiles.filter(t => !G.isWater(t) && t.terrain !== 'mountain' && t.settlement == null && G.dist(t, g.tiles[s.tile]) > 10)[0]; G.setUnitTile(g, u, far.i); assert(G.orderCost(g, u) === 3, 'far costs 3'); far.owner = s.id; far.road = true; p._fx = null; assert(G.orderCost(g, u) === 1, 'Rome: own road costs 1'); assert(G.commandMax(g, p) === G.COMMAND_BASE + 1 + (G.COMMAND_BUILDINGS.palace || 0) + 1, 'Rome: +1 Command (' + G.commandMax(g, p) + ')'); }
{ const g = fresh('shawnee', 'tecumseh', false); const p = G.player(g), s = found(g, p); const u = G.spawnUnit(g, p.idx, 'warrior', s.tile); const far = g.tiles.filter(t => !G.isWater(t) && t.terrain !== 'mountain' && t.settlement == null && G.dist(t, g.tiles[s.tile]) > 10)[0]; G.setUnitTile(g, u, far.i); assert(G.orderCost(g, u) === 2, 'Shawnee: far costs 2'); }
{ const g = fresh('persia', 'cyrus', false); const p = G.player(g); found(g, p); assert(G.commandMax(g, p) === G.COMMAND_BASE + 1 + (G.COMMAND_BUILDINGS.palace || 0) + 2, 'Persia: +2 Command (' + G.commandMax(g, p) + ')'); }
// unrest: Cyrus none, Suleiman half
{ const g = fresh('persia', 'cyrus', false); const p = G.player(g); found(g, p); const o = g.civs.filter(c => !c.minor && c.idx !== p.idx)[0]; const os = G.civSettlements(g, o.idx)[0] || G.foundSettlement(g, o.idx, g.tiles.filter(t => !G.isWater(t) && t.terrain !== 'mountain' && t.settlement == null && t.owner < 0)[5].i); G.declareWar(g, p.idx, o.idx); const u = G.spawnUnit(g, p.idx, 'warrior', os.tile); os.hp = 1; U.captureSettlement(g, os, p.idx, u); assert(!(os.unrest > g.turn), 'Cyrus: no unrest after capture (' + os.unrest + ' vs turn ' + g.turn + ')'); }
{ const g = fresh('ottoman', 'suleiman', false); const p = G.player(g); found(g, p); const o = g.civs.filter(c => !c.minor && c.idx !== p.idx)[0]; const os = G.civSettlements(g, o.idx)[0] || G.foundSettlement(g, o.idx, g.tiles.filter(t => !G.isWater(t) && t.terrain !== 'mountain' && t.settlement == null && t.owner < 0)[5].i); G.declareWar(g, p.idx, o.idx); const u = G.spawnUnit(g, p.idx, 'warrior', os.tile); os.hp = 1; U.captureSettlement(g, os, p.idx, u); assert(os.unrest === g.turn + 5, 'Suleiman: unrest halved (' + (os.unrest - g.turn) + ')'); }
// Warbands: Mongolia four fighters, Zulu heavier strikes
{ const g = fresh('mongolia', 'genghis', true); const p = G.player(g), s = found(g, p); assert(WB.maxFor(g, p.idx) === 4, 'Mongolia: four fighters'); const t = g.tiles.filter(x => !G.isWater(x) && x.terrain !== 'mountain' && x.settlement == null)[3].i; const us = [0, 1, 2, 3].map(() => G.spawnUnit(g, p.idx, 'warrior', t)); assert(WB.fighters(g, t, p.idx).length === 4, 'four fighters on one tile'); assert(G.commandMax(g, p) === G.COMMAND_BASE + 1 + (G.COMMAND_BUILDINGS.palace || 0) + 2, 'Genghis: +2 Command (' + G.commandMax(g, p) + ')'); }
{ const g = fresh('zulu', 'shaka', true); const p = G.player(g), s = found(g, p); const t = g.tiles.filter(x => !G.isWater(x) && x.terrain !== 'mountain' && x.settlement == null)[3].i; const us = [0, 1, 2].map(() => G.spawnUnit(g, p.idx, 'warrior', t)); const gs = WB.groupStrength(g, us, { attacking: true }); const str = U.strength(g, us[0], { attacking: true }); assert(gs.total === Math.max(1, Math.round(str * (1 + 0.8 + 0.6))), 'Zulu: 100/80/60 strikes (' + gs.total + ' vs ' + str + ')'); assert(WB.maxFor(g, p.idx) === 4, 'Shaka: four fighters'); }
// Climate: Russia's tiles never shift
{ const g = fresh('russia', 'peter', true); const p = G.player(g), s = found(g, p); s.tiles.forEach(i => { const t = g.tiles[i]; if (i !== s.tile) { t.terrain = 'tundra'; t.worked = true; } }); G.neighbors(g, g.tiles[s.tile]).forEach(i => { G.neighbors(g, g.tiles[i]).forEach(j => { if (g.tiles[j].owner < 0 && !G.isWater(g.tiles[j])) g.tiles[j].terrain = 'grassland'; }); }); const plan = AU.Climate.plan(g, 1); assert(!plan.some(c => G.tileOwnerCiv(g, g.tiles[c.i]) === p.idx), 'Russia: no owned tile in a warming plan'); }
// Smoke: Germany half from buildings, Celts double woods, Netherlands sink, Victoria gold
{ const g = fresh('germany', 'bismarck', true); const p = G.player(g), s = found(g, p); G.addBuilding(g, s, 'factory'); g.fxGen = (g.fxGen || 0) + 1; assert(AU.Smoke.detail(g, s).src.some(x => x[0] === 'factory' && x[1] === 1.5), 'Germany: Factory makes 1.5 Smoke'); }
{ const g = fresh('celts', 'boudica', true); const p = G.player(g), s = found(g, p); assert(G.civFx(g, p).forestSinkMult === 2, 'Celts: woods soak double'); }
{ const g = fresh('netherlands', 'william_orange', true); const p = G.player(g), s = found(g, p); assert(AU.Smoke.detail(g, s).sink.some(x => x[0] === 'sparks' && x[1] === 1), 'Netherlands: 1 Smoke sink'); }
{ const g = fresh('england', 'victoria', true); const p = G.player(g); assert(G.civFx(g, p).smokeGold === 1, 'Victoria: Gold per Smoke'); }
// Reforms and Insights: Maya two Reforms, Greece Influence per Insight, Korea study refund
{ const g = fresh('maya', 'pakal', true); const p = G.player(g); assert(MW.reformsPerAge(g, p) === 2 && MW.reformsLeft(g, p) === 2, 'Maya: two Reforms per age'); const st = MW.state(p); const hub = AU.V2.HUBS.filter(h => h.turning === undefined && h.branches.length >= 2)[0]; st.hubsFired[hub.id] = 1; MW.choose(g, p, hub.id, hub.branches[0].id); st.heritage = 9999; assert(MW.reform(g, p, hub.id, hub.branches[1].id), 'first reform'); assert(MW.reformsLeft(g, p) === 1 && MW.reform(g, p, hub.id, hub.branches[0].id), 'second reform'); assert(!MW.canReform(g, p, hub.id), 'third refused'); }
{ const g = fresh('greece', 'pericles', true); const p = G.player(g); p.influence = 0; const st = MW.state(p); const hub = AU.V2.HUBS.filter(h => h.turning === undefined)[0]; st.hubsFired[hub.id] = 1; MW.choose(g, p, hub.id, hub.branches[0].id); assert(p.influence === 15, 'Greece: +15 Influence per Insight (' + p.influence + ')'); }
{ const g = fresh('korea', 'sejong', true); const p = G.player(g), st = MW.state(p); const n = MW.openNodes(0).filter(x => x.pool === 'foundation' && !x.cheap)[0]; const c = MW.studyCost(g, p, n); st.study = c; assert(MW.study(g, p, n.id), 'studied'); assert(st.study === Math.round(c * 0.25), 'Korea: a quarter refunded (' + st.study + ')'); }
// Synthesis: Babylon cheaper, Peter +3 supply; Bonds: Carthage half upkeep
{ const g = fresh('babylon', 'hammurabi', true); const p = G.player(g); assert(SY.cost(g, p) === Math.round(300 * 0.75 * G.speed(g)), 'Babylon: Synthesis 25% cheaper (' + SY.cost(g, p) + ')'); }
{ const g = fresh('russia', 'peter', true); const p = G.player(g); assert(SY.supplyFor(g, p) === 3, 'Peter: +3 supply'); }
{ const g = fresh('carthage', 'dido', true); const p = G.player(g); p.bonds = ['x', 'y']; assert(SO.bondUpkeep(g, p) === 2, 'Carthage: half upkeep (' + SO.bondUpkeep(g, p) + ')'); }
console.log('synergy tests OK');
