// Chibipedia: every game object, generated from the data files, with cross-links and search.
(function (AU) {
  var G = AU.G, P = AU.Panels;
  var $ = function (id) { return document.getElementById(id); };
  function y(o, plus) { if (!o) return ''; var map = { food: '🌾', production: '⚙️', gold: '💰', science: '🔬', culture: '🎭', faith: '🕊️', happiness: '😊' }; return AU.YIELD_KEYS.filter(function (k) { return o[k]; }).map(function (k) { return map[k] + (plus && o[k] > 0 ? '+' : '') + o[k]; }).join(' '); }
  function link(cat, id, text) { return '<a class="plink" data-action="pedia" data-cat="' + cat + '" data-id="' + id + '">' + text + '</a>'; }
  // ---- artwork helpers: what pictures exist (from the generated asset list or the inlined data) ----
  var artSet = null;
  function artIndex() {
    if (artSet) return artSet; artSet = {};
    (AU.ASSET_LIST || []).forEach(function (pth) { artSet[pth.replace(/^assets\//, '').replace(/\.(png|jpg)$/, '')] = true; });
    if (AU.ASSET_DATA) for (var k in AU.ASSET_DATA) artSet[k] = true;
    return artSet;
  }
  function artHas(kind, id) { return !!artIndex()[kind + '/' + id]; }
  function thumb(kind, id, label, big) { return '<div class="art-thumb' + (big ? ' big' : '') + '"><img loading="lazy" src="' + AU.Assets.url(kind, id) + '" alt=""><small>' + label + '</small></div>'; }
  var ART_KINDS = [['units', 'Units'], ['buildings', 'Buildings'], ['wonders', 'World Wonders'], ['national', 'National Wonders'], ['natural', 'Natural Wonders'], ['leaders', 'Leaders'], ['civs', 'Empire emblems'], ['resources', 'Resources'], ['features', 'Features & improvements'], ['techs', 'Technology cards'], ['civics', 'Civic cards'], ['thrones', 'Throne rooms'], ['palace', 'Palace pieces'], ['keyart', 'Key art & logo']];
  function artKindCount(kind) { var n = 0, ix = artIndex(); for (var k in ix) if (k.indexOf(kind + '/') === 0) n++; return n; }
  // every version of one unit or building: the shared picture plus one per cultural art group
  function variantsHtml(kind, id) {
    var out = ''; if (artHas(kind, id)) out += thumb(kind, id, 'Shared');
    for (var c in AU.CULTURES) if (artHas(kind + '/' + c, id)) out += thumb(kind + '/' + c, id, AU.CULTURES[c].name);
    return out ? '<div class="art-grid">' + out + '</div>' : '';
  }
  function artEntry(kind) {
    var h = '', ix = artIndex();
    if (kind === 'units' || kind === 'buildings') {
      var src = kind === 'units' ? AU.UNITS : AU.BUILDINGS;
      for (var id in src) { var v = variantsHtml(kind, id); if (v) h += '<h4>' + (src[id].icon ? src[id].icon + ' ' : '') + src[id].name + '</h4>' + v; }
      if (kind === 'units') { var uuRow = ''; AU.CIVS.forEach(function (cc) { if (cc.uu && artHas('units', cc.uu.id)) uuRow += thumb('units', cc.uu.id, cc.uu.name + ' (' + cc.name + ')'); }); if (uuRow) h += '<h4>★ Unique units</h4><div class="art-grid">' + uuRow + '</div>'; }
    } else if (kind === 'palace') {
      for (var st in AU.PALACE_STYLES) { var row = ''; AU.PALACE_PIECES.forEach(function (pc) { if (artHas('palace/' + st, pc.id)) row += thumb('palace/' + st, pc.id, pc.name); }); if (row) h += '<h4>' + AU.PALACE_STYLES[st].name + ' style</h4><div class="art-grid">' + row + '</div>'; }
    } else {
      var names = {};
      if (kind === 'wonders') for (var w in AU.WONDERS) names[w] = AU.WONDERS[w].name;
      if (kind === 'national') for (var nw in AU.NATIONAL) names[nw] = AU.NATIONAL[nw].name;
      if (kind === 'natural') for (var na in AU.NATURAL_WONDERS) names[na] = AU.NATURAL_WONDERS[na].name;
      if (kind === 'leaders') for (var l in AU.LEADER_BY_ID) names[l] = AU.LEADER_BY_ID[l].name + ' (' + AU.CIV_BY_ID[AU.LEADER_BY_ID[l].civId].name + ')';
      if (kind === 'civs') for (var cv in AU.CIV_BY_ID) names[cv] = AU.CIV_BY_ID[cv].name;
      if (kind === 'resources') for (var r in AU.RESOURCES) names[r] = AU.RESOURCES[r].name;
      if (kind === 'features') { for (var f in AU.FEATURES) names[f] = AU.FEATURES[f].name; for (var im in AU.IMPROVEMENTS) names[im] = AU.IMPROVEMENTS[im].name; names.mountain = 'Mountain'; names.hills = 'Hills'; names.raider_camp = 'Raider camp'; }
      if (kind === 'terrain') { for (var t in AU.TERRAIN) names[t] = AU.TERRAIN[t].name; for (var f2 in AU.FEATURES) names[f2] = AU.FEATURES[f2].name; names.hills = 'Hills'; }
      if (kind === 'techs') AU.TECHS.forEach(function (t) { names[t.id] = t.name; });
      if (kind === 'civics') AU.CIVICS.forEach(function (c) { names[c.id] = c.name; });
      if (kind === 'thrones') for (var cu in AU.CULTURES) names[cu] = AU.CULTURES[cu].name;
      if (kind === 'keyart') { names.title_landscape = 'Title (landscape)'; names.title_portrait = 'Title (portrait)'; for (var lg in ix) if (lg.indexOf('logo/') === 0) row2 += thumb('logo', lg.slice(5), 'Logo ' + lg.slice(5).replace('tiny_empires_', ''), true); }
      var row2 = row2 || '', big = kind === 'keyart' || kind === 'leaders' || kind === 'natural' || kind === 'wonders' || kind === 'national' || kind === 'thrones' || kind === 'techs' || kind === 'civics';
      for (var k in ix) { if (k.indexOf(kind + '/') !== 0 || k.slice(kind.length + 1).indexOf('/') >= 0) continue; var id2 = k.slice(kind.length + 1); row2 += thumb(kind, id2, names[id2] || id2, big); }
      if (row2) h += '<div class="art-grid">' + row2 + '</div>';
    }
    return h || '<p class="stat">No pictures of this kind yet. They appear here as soon as they are generated.</p>';
  }
  function fxText(fx) { return AU.civicFxText({ fx: fx }) || ''; }
  function quoteOf(cat, id) { var q = AU.QUOTES && AU.QUOTES[cat] && AU.QUOTES[cat][id]; return q ? '<blockquote class="pquote">“' + q.text + '”<div class="quote-by">— ' + q.by + '</div></blockquote>' : ''; }

  var CATS = [
    ['concepts', 'Concepts'], ['art', 'Art gallery'], ['civs', 'Empires'], ['leaders', 'Leaders'], ['units', 'Units'], ['buildings', 'Buildings'], ['wonders', 'World Wonders'], ['national', 'National Wonders'],
    ['natural', 'Natural Wonders'], ['techs', 'Technologies'], ['civics', 'Civics'], ['governments', 'Governments'], ['policies', 'Policy Cards'], ['terrain', 'Terrain & Features'], ['resources', 'Resources'], ['improvements', 'Improvements'], ['specializations', 'Town Specializations'], ['promotions', 'Promotions'], ['pantheons', 'Pantheons'], ['beliefs', 'Devout Beliefs'], ['citystates', 'City-States']
  ];
  var CONCEPTS = {
    towns_cities: ['Towns and Cities', 'Your capital is a City. Every other settlement you found is a Town. Towns have no production queue: their production is converted to Gold and you purchase buildings and units in them. Towns grow on their own and, from 5 population, can be specialized (Farming, Mining, Trade Outpost, Fort, Urban Center). A specialized Town stops growing and sends its surplus food to your nearest City. Pay Gold to upgrade a Town into a City with a real production queue; the price rises with each City you own.'],
    growth: ['Growth and tiles', 'Each settlement starts with its centre and the six tiles around it. Every time it grows, the new citizen claims and works one tile within three rings (four with some abilities), and that tile is improved automatically: farm, mine, pasture, plantation, quarry, camp, woodcutter or fishing boats depending on the terrain. Food beyond 2 per citizen fills the growth bar; starvation shrinks a settlement. Once all tiles are claimed, new citizens become specialists worth Knowledge and Heritage.'],
    happiness: ['Happiness', 'Each settlement starts with 3 Happiness and loses 1 per 2 population. Buildings, worked Luxury resources (up to 4, empire-wide), governments, civics, policies and wonders add to it; war weariness subtracts. Below 0 the settlement produces 15% less (30% below -5) and grows at half speed.'],
    research: ['Research, sparks, insights and mastery', 'Knowledge fills the technology you are researching; Heritage fills the civic. Every technology has a Spark and every civic an Inspiration: an in-game condition (work a mine, meet an empire, kill a unit with a slinger…). Meeting it does not make the research cheaper by itself (only a few leaders, such as Meiji and Pericles, gain Knowledge or Heritage from it): its reward is Mastery. every technology and civic also carries a permanent bonus (Archery: ranged units 15% cheaper, Irrigation: farms +1 Food, Sanitation: +15% growth…). You earn it by completing the technology or civic AFTER its Spark or Insight fired. Complete it without the Spark and that mastery is lost for the rest of the game, so it pays to chase the conditions before you research. One continuous tree of 104 technologies and 60 civics spans eight eras with no resets.'],
    government: ['Governments and policies', 'Civics unlock governments. Each government has a bonus and a set of card slots: military, economic, diplomatic and wildcard. Policy cards are unlocked by civics and can be swapped at any time from the Civics panel. Wildcard slots take any card.'],
    citystates: ['Free cities, Ties and Unions', 'Free cities are independent single-city powers of six kinds (Trade, Scholarly, Artistic, Devout, Martial, Industrial). There are no tokens to send: your Ties (0 to 100) with each free city grow from what you do on the map. A Caravan (needs the Caravans civic; you may keep one plus one per Market or Harbor) parked inside their land opens a trade route worth Gold every turn and +3 Ties; a military unit standing in their land adds +1 (protection); sharing a religion adds +1; completing their quest gives +15 and a gift gives +10 (120 Gold plus 3 per Tie you already have, one every 15 turns); the first empire to find them starts at 10. Gifts, quests and reputation can only carry you to 75: above that only caravans, garrisons and shared faith count, and a Patron who stops showing up slips back by 1 per turn. Ties also fade by 1 per turn when nothing has fed them for 10 turns. Tiers: Acquaintance (10), Partner (30: their yield in your capital), Patron (60 and nobody closer: their special bonus, more yields, and they fight your wars), Kin (90 as Patron: even more yields). After 20 turns as Kin with borders touching, you can propose a Union: the free city joins you peacefully as a Town and its special bonus stays with you forever. Attacking any free city drops your Ties with all of them to zero for 30 turns.'],
    religion: ['Religion and Devotion', 'Shrines (+2 Devotion) and Temples (+4, after Theology) produce Devotion. With 25 Devotion you choose a Pantheon: one small permanent belief. With a pantheon and a Great Prophet (earned with Great Prophet points from Shrines, Temples and your Devotion income) you found a religion in the settlement where the prophet stands, which becomes its Holy City: pick a name, a Follower belief (every settlement that follows the religion gets it) and a Founder belief (rewards you for every settlement in the world following it). Only about half as many religions as empires can exist. Religion spreads by pressure from settlements that follow it (holy cities push harder, up to 9 tiles) and through Preachers (bought with Devotion in a settlement with a Shrine) and Evangelists and Faith Wardens (Temple). Evangelists debate enemy religious units next to them; Faith Wardens purge foreign religions from your settlements. Enhancing your religion adds an Enhancer belief and a second Follower belief. Devout victory (from the Renaissance era on): your religion is the majority in at least half of every empire\'s settlements.'],
    promotions: ['Experience and promotions', 'Units earn experience in combat (1 XP per attack, 3 per kill, 3 for surviving an attack). At 5, 12, 24 and 40 XP they gain a level: +2 Strength and one promotion of your choice from their class list, which also heals 50 HP. Melee and anti-cavalry, ranged and siege, cavalry, naval and recon units each have their own promotions; higher tiers unlock at higher levels. The AI promotes automatically.'],
    combat: ['Combat', 'Damage is 30 × e^(0.04 × strength difference), with ±20% variance. Ranged units strike without taking damage; melee attackers take damage back. Counters: anti-cavalry units (Spear Guard, Pike Guard, Fusilier…) get +10 Strength against cavalry; cavalry gets +5 against ranged and siege units; siege units are strong against settlements and weak in the open. Flanking: a melee or cavalry attacker gets +2 Strength for every friendly military unit adjacent to it (up to +6), and a defender gets the same support bonus from its own neighbours; promotions such as Shield Wall add more. Some leaders and empires add class bonuses of their own. Settlements with Walls or a Castle bombard the strongest enemy unit within 2 tiles every turn. Hills and forests give +3 defence, fortifying up to +6. Units lose strength as they are wounded. Units heal when they do not act; faster inside your borders and in settlements. Experience earns levels worth +3 Strength each. One military and one civilian unit per tile.'],
    settlements_war: ['Sieging settlements', 'A settlement has 100 HP (+100 with Walls, +100 more with a Castle) and a defence value based on the best unit its owner can build plus walls, hills and garrison. Walls let it fire at adjacent enemies every turn. Ranged non-siege units deal half damage to settlements. When its HP reaches 0, a melee, anti-cavalry, cavalry or recon unit can move in and capture it; capturing a capital moves the palace to the victim\'s largest remaining settlement. An empire with no settlements is destroyed.'],
    independents: ['Inchibils', 'The Inchibils are the wild people of the world: not an empire, not a Free city, nobody to talk to. Their camps (🏕️) sit in the wilderness and periodically release raiders that attack nearby units and settlements. Move a military unit onto a camp to disperse it for Gold (a big reward card tells you when you do). The raiders grow stronger as the world advances through the eras. Free cities, by contrast, are real single-city powers with a leader you can build Ties with.'],
    diplomacy: ['Diplomacy', 'Every leader keeps an attitude toward you, moved by wars, border tension, your abilities and time. Declare war from the Diplomacy panel; the AI proposes peace when a war goes badly for it and accepts peace after at least 8 turns of war when it is losing or not hostile. Peace treaties last 10 turns.'],
    palace: ['Your Palace', 'As your people prosper they offer to add a piece to your palace. A piece is offered when a new era begins, when you complete a wonder, and every 20 turns while your empire is content (happiness not negative). Twelve pieces exist (hall, wings, towers, crown, gate, walls, gardens, fountain, monument, banners), each built in one of eleven architectural styles (Classical, Gothic, Pagoda, Mughal, Persian, Sahelian, Stepped and more) that you may mix freely. Every piece gives +1 Heritage in the capital and +1 tourism; every four pieces give +1 Happiness in every settlement. Open it from the Empire panel.'],
    diplomacy: ['Diplomacy and leaders', 'Meeting a leader opens an audience (a leader screen). Every leader follows an agenda drawn from their personality (Iron Fist, Manifest Destiny, Enlightened, Patron of the Arts, True Devotion, Peace and Plenty) and judges you by it every 10 turns; the screen lists what they like and dislike about you. Ways to improve relations: delegations (30 Gold), gifts (100 Gold), luxury trades, peace. A Declaration of Friendship (30 turns) forbids war between you; after 8 turns of friendship a high opinion allows an Alliance (40 turns): open borders, shared map knowledge and each side joins the war if the other is attacked. Open borders let military units cross territory. Denouncing a leader hurts their opinion and that of their friends, and pleases their enemies. Breaking a friendship by declaring war is remembered by every leader. Free cities: see the Free cities entry for Ties, caravans, quests, gifts and Unions.'],
    wonders: ['Wonders', 'World Wonders can be built once in the whole world, only in Cities, and often need a specific site (coast, river, desert, hills). National Wonders can be built once per empire and usually require several copies of a building across your settlements. Natural Wonders are placed by the map: working or neighbouring them yields strong bonuses and discovering one grants Knowledge and Heritage (double for the first empire to find it).'],
    victory: ['Victory', 'Heritage: accumulate Fame (wonders, museums, amphitheaters, broadcast towers, stadiums, natural wonders in your borders) until your foreign visitors outnumber the domestic tourists of every rival, from the Industrial era on. Domination: hold every rival\'s original capital. Knowledge: research Spaceflight, build a Spaceport and complete Launch Earth Satellite, Moon Landing and Launch Colony Ship in your capital. Score: the highest score when the turn limit of the chosen game speed is reached.'],
    great_people: ['Great People', 'Seven kinds of Great People join your empire over the game: Prophets, Scientists, Engineers, Merchants, Artists, Generals and Admirals. Each kind has its own points, earned every turn by buildings and wonders (Shrines and Temples for Prophets, Libraries and Universities for Scientists, Workshops and Factories for Engineers, Markets and Banks for Merchants, Amphitheaters and Museums for Artists, Barracks and Military Academies for Generals, Lighthouses and Harbors for Admirals; many wonders add points too). When the points reach the cost, the Great Person appears in your capital as a unit; the cost rises with every one you recruit. From half way you can recruit early with Devotion or Gold (Empire panel). What they do: a Prophet founds a religion in the settlement it stands in (the only way to found one); a Scientist completes the technology you are researching; an Engineer adds a big burst of Production to a City\'s current build; a Merchant brings Gold and +15 Ties with every free city; an Artist creates a Great Work (+3 Heritage, +3 Fame in that settlement forever); a General gives +5 Strength to your land units within 2 tiles while alive and can retire to heal them; an Admiral does the same for ships and gives them +1 Movement. Great People are civilians: keep them away from enemies.'],
    speeds: ['Game speeds', 'Quick (×0.67 costs, 330 turns), Standard (×1, 500 turns), Epic (×1.5, 750 turns) and Marathon (×3, 1500 turns) scale research, production, growth, upgrade costs and the turn limit.']
  };

  function entries(cat) {
    var out = [];
    switch (cat) {
      case 'concepts': for (var c in CONCEPTS) out.push({ id: c, name: CONCEPTS[c][0] }); break;
      case 'civs': AU.CIVS.forEach(function (c) { out.push({ id: c.id, name: c.name }); }); break;
      case 'leaders': AU.CIVS.forEach(function (c) { c.leaders.forEach(function (l) { out.push({ id: l.id, name: l.name + ' (' + c.name + ')' }); }); }); break;
      case 'art': ART_KINDS.forEach(function (k) { var n = artKindCount(k[0]); out.push({ id: k[0], name: k[1], sub: n + (n === 1 ? ' picture' : ' pictures') }); }); break;
      case 'units': for (var u in AU.UNITS) out.push({ id: u, name: AU.UNITS[u].name }); break;
      case 'promotions': AU.PROMOTIONS.forEach(function (pr) { out.push({ id: pr.id, name: pr.name }); }); break;
      case 'citystates': AU.CITY_STATES.forEach(function (c) { out.push({ id: c.id, name: c.name }); }); break;
      case 'pantheons': AU.PANTHEONS.forEach(function (b) { out.push({ id: b.id, name: b.name }); }); break;
      case 'beliefs': AU.FOLLOWER_BELIEFS.concat(AU.FOUNDER_BELIEFS, AU.ENHANCER_BELIEFS).forEach(function (b) { out.push({ id: b.id, name: b.name }); }); break;
      case 'buildings': for (var b in AU.BUILDINGS) if (!AU.BUILDINGS[b].noBuild) out.push({ id: b, name: AU.BUILDINGS[b].name }); break;
      case 'wonders': for (var w in AU.WONDERS) out.push({ id: w, name: AU.WONDERS[w].name }); break;
      case 'national': for (var n in AU.NATIONAL) out.push({ id: n, name: AU.NATIONAL[n].name }); break;
      case 'natural': for (var nw in AU.NATURAL_WONDERS) out.push({ id: nw, name: AU.NATURAL_WONDERS[nw].name }); break;
      case 'techs': AU.TECHS.forEach(function (t) { out.push({ id: t.id, name: t.name, sub: AU.ERAS[t.era] }); }); break;
      case 'civics': AU.CIVICS.forEach(function (t) { out.push({ id: t.id, name: t.name, sub: AU.ERAS[t.era] }); }); break;
      case 'governments': for (var gv in AU.GOVERNMENTS) out.push({ id: gv, name: AU.GOVERNMENTS[gv].name }); break;
      case 'policies': for (var pc in AU.POLICIES) out.push({ id: pc, name: AU.POLICIES[pc].name, sub: AU.POLICIES[pc].type }); break;
      case 'terrain': for (var t in AU.TERRAIN) out.push({ id: 't:' + t, name: AU.TERRAIN[t].name }); out.push({ id: 'hills', name: 'Hills' }); out.push({ id: 'river', name: 'River' }); out.push({ id: 'navigable', name: 'Navigable River' }); for (var f in AU.FEATURES) out.push({ id: 'f:' + f, name: AU.FEATURES[f].name }); break;
      case 'resources': for (var r in AU.RESOURCES) out.push({ id: r, name: AU.RESOURCES[r].name, sub: AU.RESOURCES[r].kind }); break;
      case 'improvements': for (var im in AU.IMPROVEMENTS) out.push({ id: im, name: AU.IMPROVEMENTS[im].name }); break;
      case 'specializations': for (var sp in AU.SPECIALIZATIONS) out.push({ id: sp, name: AU.SPECIALIZATIONS[sp].name }); break;
    }
    return out;
  }
  function techsUnlocking(pred) { var out = []; AU.TECHS.forEach(function (t) { if (pred(t)) out.push(link('techs', t.id, t.name)); }); return out; }
  function unitReq(d) { return (d.tech ? 'Requires ' + link('techs', d.tech, AU.TECH_BY_ID[d.tech].name) : 'Available from the start') + (d.resource ? ' and ' + link('resources', d.resource, AU.RESOURCES[d.resource].name) : ''); }
  function entry(cat, id) {
    var h = '';
    switch (cat) {
      case 'concepts': { var c = CONCEPTS[id]; if (!c) return ''; h = '<h3>' + c[0] + '</h3><p>' + c[1] + '</p>'; break; }
      case 'art': { var ak = ART_KINDS.filter(function (k) { return k[0] === id; })[0]; if (!ak) return ''; h = '<h3>🎨 ' + ak[1] + ' <span class="pill">' + artKindCount(id) + ' pictures</span></h3><p class="stat">Every picture the game currently has of this kind. Units and buildings show the shared picture and each cultural version (the game picks the version of the empire\'s art group).</p>' + artEntry(id); break; }
      case 'civs': { var cv = AU.CIV_BY_ID[id]; if (!cv) return ''; h = '<h3><span class="swatch" style="display:inline-block;width:14px;height:14px;background:' + cv.color + ';border:2px solid ' + cv.color2 + ';border-radius:3px"></span> ' + cv.name + '</h3><p><span class="pill">' + (AU.CULTURES[cv.culture] ? AU.CULTURES[cv.culture].name + ' art group' : '') + '</span> <span class="pill">' + (cv.difficulty || 'medium') + '</span></p><p><b>' + cv.ability.name + ':</b> ' + cv.ability.desc + '</p>' + (cv.ui ? '<p><b>Unique improvement:</b> ' + cv.ui.icon + ' ' + cv.ui.name + ' (instead of the ' + AU.IMPROVEMENTS[cv.ui.replaces].name + (cv.ui.when ? ' on ' + AU.whenLabel(cv.ui.when) + ' tiles' : '') + '): ' + cv.ui.desc + '</p>' : '') + (cv.ut ? '<p><b>Unique town:</b> ' + cv.ut.icon + ' ' + cv.ut.name + ' (a specialization only this empire can pick, pop ' + cv.ut.minPop + '): ' + cv.ut.desc + '</p>' : '') + (cv.uu ? '<p><b>Unique unit:</b> ' + link('units', cv.uu.replaces, cv.uu.name) + ' (replaces ' + AU.UNITS[cv.uu.replaces].name + ', ' + cv.uu.desc + ').</p>' + (artHas('units', cv.uu.id) ? '<div class="art-grid">' + thumb('units', cv.uu.id, cv.uu.name) + '</div>' : '') : '') + (cv.ub ? '<p><b>Unique building:</b> ' + link('buildings', cv.ub.replaces, cv.ub.name) + ' (replaces ' + AU.BUILDINGS[cv.ub.replaces].name + ', ' + cv.ub.desc + ').</p>' : '') + '<p><b>Leaders:</b> ' + cv.leaders.map(function (l) { return link('leaders', l.id, l.name); }).join(', ') + '</p><p><b>Settlement names:</b> ' + cv.cities.join(', ') + '</p>'; break; }
      case 'leaders': { var l = AU.LEADER_BY_ID[id]; if (!l) return ''; var lc = AU.CIV_BY_ID[l.civId]; h = (artHas('leaders', id) ? '<img class="pedia-pic" src="' + AU.Assets.url('leaders', id) + '" alt="">' : '') + '<h3>' + l.name + '</h3><p>' + l.title + ' of ' + link('civs', lc.id, lc.name) + '. Leans towards a ' + AU.leaningText(l) + ' victory. A leader can only rule their own empire.</p><p><b>' + l.ability.name + ':</b> ' + l.ability.desc + '</p><p><b>Empire ability, ' + lc.ability.name + ':</b> ' + lc.ability.desc + '</p><p class="stat">AI personality: aggression ' + Math.round(l.ai.aggression * 100) + '%, expansion ' + Math.round(l.ai.expansion * 100) + '%, science ' + Math.round(l.ai.science * 100) + '%, culture ' + Math.round(l.ai.culture * 100) + '%.</p>'; break; }
      case 'citystates': { var cs = AU.CITY_STATE_BY_ID[id]; if (!cs) return ''; var T = AU.CITY_STATE_TYPES[cs.type]; var tn = ['Partner (30 Ties)', 'Patron (60 Ties, closest empire)', 'Kin (90 Ties as Patron)']; h = '<h3>' + T.icon + ' ' + cs.name + '</h3><p>' + T.name + ' free city.</p><p>' + AU.ENVOY_TIERS(cs.type).map(function (t, i) { return tn[i] + ': ' + t.desc; }).join('. ') + '.</p><p><b>' + cs.ability.name + ' (Patron):</b> ' + cs.ability.desc.replace(/^Suzerain: /, '') + '</p>'; break; }
      case 'pantheons': case 'beliefs': { var bl = AU.BELIEF_BY_ID[id]; if (!bl) return ''; h = '<h3>🕊️ ' + bl.name + '</h3><p>' + ({ pantheon: 'Pantheon belief', follower: 'Follower belief', founder: 'Founder belief', enhancer: 'Enhancer belief' }[bl.type]) + '.</p><p>' + bl.desc + '</p>'; break; }
      case 'promotions': { var pr = AU.PROMO_BY_ID[id]; if (!pr) return ''; h = '<h3>⭐ ' + pr.name + '</h3><p>' + ({ melee: 'Melee and anti-cavalry', ranged: 'Ranged and siege', cavalry: 'Cavalry', naval: 'Naval', recon: 'Recon' }[pr.fam]) + ' promotion, tier ' + pr.tier + ' (available from level ' + pr.tier + ').</p><p>' + AU.modsText(pr.mods) + '.</p>'; break; }
      case 'units': { var u = AU.UNITS[id]; if (!u) return ''; h = '<h3>' + u.icon + ' ' + u.name + '</h3><p>Class ' + (u.religious ? 'religious' : u.cls) + ' · ' + (u.religious ? 'Cost ' + u.faithCost + ' 🕊️ Devotion' : 'Cost ' + u.cost + ' ⚙️') + ' · Moves ' + u.moves + (u.strength ? ' · Strength ' + u.strength : '') + (u.ranged ? ' · Ranged ' + u.ranged + ' (range ' + u.range + ')' : '') + (u.sight ? ' · Sight ' + u.sight : '') + '</p><p>' + (u.religious ? (id === 'missionary' ? 'Requires a founded religion and a Shrine or Temple in the settlement; bought with Devotion, never built' : 'Requires a founded religion and a Temple in the settlement; bought with Devotion, never built') : unitReq(u)) + '.' + (u.upgradesTo ? ' Upgrades to ' + link('units', u.upgradesTo, AU.UNITS[u.upgradesTo].name) + '.' : '') + (u.desc ? ' ' + u.desc : '') + '</p>';
        var uv = variantsHtml('units', id); if (uv) h += '<p><b>Artwork:</b></p>' + uv;
        var uniques = AU.CIVS.filter(function (cc) { return cc.uu && cc.uu.replaces === id; }); if (uniques.length) { h += '<p><b>Unique versions:</b> ' + uniques.map(function (cc) { return cc.uu.name + ' (' + link('civs', cc.id, cc.name) + ': ' + cc.uu.desc + ')'; }).join('; ') + '</p>'; var ut = uniques.filter(function (cc) { return artHas('units', cc.uu.id); }).map(function (cc) { return thumb('units', cc.uu.id, cc.uu.name); }).join(''); if (ut) h += '<div class="art-grid">' + ut + '</div>'; } break; }
      case 'buildings': { var b = AU.BUILDINGS[id]; if (!b) return ''; h = '<h3>' + b.name + '</h3><p>' + y(b.yields, true) + ' · Cost ' + b.cost + ' ⚙️</p><p>' + (b.tech ? 'Requires ' + link('techs', b.tech, AU.TECH_BY_ID[b.tech].name) : b.civic ? 'Requires civic ' + link('civics', b.civic, AU.CIVIC_BY_ID[b.civic].name) : 'Available from the start') + (b.requires ? ', needs ' + link('buildings', b.requires, AU.BUILDINGS[b.requires].name) : '') + (b.needs ? ', settlement must have ' + b.needs : '') + (b.resource ? ', needs ' + link('resources', b.resource, AU.RESOURCES[b.resource].name) : '') + '.</p>' + (b.desc ? '<p>' + b.desc + '</p>' : '') + (b.perPop ? '<p>+' + b.perPop.science + ' Knowledge per population.</p>' : '') + (b.pct ? '<p>+' + Object.values(b.pct)[0] + '% ' + Object.keys(b.pct)[0] + '.</p>' : '');
        var ubs = AU.CIVS.filter(function (cc) { return cc.ub && cc.ub.replaces === id; }); if (ubs.length) h += '<p><b>Unique versions:</b> ' + ubs.map(function (cc) { return cc.ub.name + ' (' + link('civs', cc.id, cc.name) + ': ' + cc.ub.desc + ')'; }).join('; ') + '</p>';
        var nat = Object.keys(AU.NATIONAL).filter(function (n) { return AU.NATIONAL[n].requiresCount && AU.NATIONAL[n].requiresCount[0] === id; }); if (nat.length) h += '<p>Counts toward ' + nat.map(function (n) { return link('national', n, AU.NATIONAL[n].name); }).join(', ') + '.</p>'; var bv = variantsHtml('buildings', id); if (bv) h += '<p><b>Artwork:</b></p>' + bv; break; }
      case 'wonders': { var w = AU.WONDERS[id]; if (!w) return ''; h = '<h3>🏛️ ' + w.name + '</h3><p>' + y(w.yields, true) + ' · Cost ' + w.cost + ' ⚙️ · ' + (w.tech ? 'Requires ' + link('techs', w.tech, AU.TECH_BY_ID[w.tech].name) : 'Requires civic ' + link('civics', w.civic, AU.CIVIC_BY_ID[w.civic].name)) + (w.needs ? ' · Needs ' + w.needs : '') + '</p><p>' + w.desc + '</p><p class="stat">World wonder: only one can exist in the whole world.</p>' + quoteOf('wonder', id); break; }
      case 'national': { var nw = AU.NATIONAL[id]; if (!nw) return ''; h = '<h3>🏯 ' + nw.name + '</h3><p>' + y(nw.yields, true) + ' · Cost ' + nw.cost + ' ⚙️ · ' + (nw.tech ? 'Requires ' + link('techs', nw.tech, AU.TECH_BY_ID[nw.tech].name) : 'Requires civic ' + link('civics', nw.civic, AU.CIVIC_BY_ID[nw.civic].name)) + (nw.requiresCount ? ' · Needs ' + nw.requiresCount[1] + '× ' + link('buildings', nw.requiresCount[0], AU.BUILDINGS[nw.requiresCount[0]].name) : '') + '</p><p>' + nw.desc + '</p><p class="stat">National wonder: one per empire, Cities only.</p>' + quoteOf('national', id); break; }
      case 'natural': { var nn = AU.NATURAL_WONDERS[id]; if (!nn) return ''; h = '<h3>' + nn.icon + ' ' + nn.name + '</h3><p>Found on ' + nn.terrain + (nn.hills ? ' hills' : '') + ' · Tile yields ' + y(nn.yields) + ' · Adjacent worked tiles ' + y(nn.adjacent, true) + '</p><p>' + nn.desc + '</p><p class="stat">Discovering it grants Knowledge and Heritage (double for the first empire).</p>' + quoteOf('natural', id); break; }
      case 'techs': { var t = AU.TECH_BY_ID[id]; if (!t) return ''; var leads = AU.TECHS.filter(function (x) { return x.pre.indexOf(id) >= 0; }); h = (AU.Assets.get('techs', id) ? '<img class="pedia-pic" src="' + AU.Assets.url('techs', id) + '" alt="">' : '') + '<h3>' + t.name + ' <span class="pill">' + AU.ERAS[t.era] + '</span></h3><p>Base cost ' + t.cost + ' 🔬' + (t.pre.length ? ' · Requires ' + t.pre.map(function (x) { return link('techs', x, AU.TECH_BY_ID[x].name); }).join(', ') : '') + '</p><p><b>Unlocks:</b> ' + (AU.unlocksOfTech(id).join(', ') || 'further technologies') + '</p>' + (t.eureka ? '<p><b>💡 Eureka:</b> ' + t.eureka.desc + '</p>' : '') + (G.masteryOf(id, false) ? '<p><b>⭐ Mastery</b> (finish it after the Spark): ' + G.masteryOf(id, false).desc + '</p>' : '') + (leads.length ? '<p><b>Leads to:</b> ' + leads.map(function (x) { return link('techs', x.id, x.name); }).join(', ') + '</p>' : '') + quoteOf('tech', id); break; }
      case 'civics': { var cc2 = AU.CIVIC_BY_ID[id]; if (!cc2) return ''; var leads2 = AU.CIVICS.filter(function (x) { return x.pre.indexOf(id) >= 0; }); h = (AU.Assets.get('civics', id) ? '<img class="pedia-pic" src="' + AU.Assets.url('civics', id) + '" alt="">' : '') + '<h3>' + cc2.name + ' <span class="pill">' + AU.ERAS[cc2.era] + '</span></h3><p>Base cost ' + cc2.cost + ' 🎭' + (cc2.pre.length ? ' · Requires ' + cc2.pre.map(function (x) { return link('civics', x, AU.CIVIC_BY_ID[x].name); }).join(', ') : '') + '</p><p><b>Effect:</b> ' + (AU.civicFxText(cc2) || '—') + '</p><p><b>Unlocks:</b> ' + (AU.unlocksOfCivic(id).join(', ') || '—') + '</p>' + (cc2.inspiration ? '<p><b>💡 Inspiration:</b> ' + cc2.inspiration.desc + '</p>' : '') + (G.masteryOf(id, true) ? '<p><b>⭐ Mastery</b> (finish it after the Insight): ' + G.masteryOf(id, true).desc + '</p>' : '') + (leads2.length ? '<p><b>Leads to:</b> ' + leads2.map(function (x) { return link('civics', x.id, x.name); }).join(', ') + '</p>' : '') + quoteOf('civic', id); break; }
      case 'governments': { var gv = AU.GOVERNMENTS[id]; if (!gv) return ''; h = '<h3>' + gv.name + '</h3><p>' + gv.desc + '</p><p><b>Slots:</b> ' + Object.keys(gv.slots).filter(function (k) { return gv.slots[k]; }).map(function (k) { return gv.slots[k] + ' ' + k; }).join(', ') + '</p><p>' + (gv.civic ? 'Unlocked by ' + link('civics', gv.civic, AU.CIVIC_BY_ID[gv.civic].name) : 'Starting government') + '.</p>'; break; }
      case 'policies': { var pc = AU.POLICIES[id]; if (!pc) return ''; var from = AU.CIVICS.filter(function (x) { return (x.cards || []).indexOf(id) >= 0; }); h = '<h3>' + pc.name + ' <span class="pill">' + pc.type + '</span></h3><p>' + pc.desc + '</p><p>Unlocked by ' + from.map(function (x) { return link('civics', x.id, x.name); }).join(', ') + '.</p>'; break; }
      case 'terrain': {
        if (id === 'hills') h = '<h3>Hills</h3><p>+1 Production, costs 2 movement, +3 defence. Mines are the default improvement. Some abilities improve hills further.</p>';
        else if (id === 'river') h = '<h3>River</h3><p>+1 Food on land tiles. Enables the Water Mill and several wonders. Settlements on rivers benefit from Egyptian and Shawnee abilities.</p>';
        else if (id === 'navigable') h = '<h3>Navigable River</h3><p>The wide lower reach of a long river. +1 Food and +1 Gold. Land units cross it like any land tile; ships can sail up it, and a settlement on or next to it counts as coastal: it can build ships, a Harbor and a Lighthouse even far from the sea. Rivers on the map: thin streams are ordinary rivers, wide ones with sandy banks are navigable.</p>';
        else if (id.charAt(0) === 't') { var tt = AU.TERRAIN[id.slice(2)]; h = '<h3>' + tt.name + '</h3><p>' + (y(tt.yields) || 'No yields') + (tt.impassable ? ' · Impassable (except for some abilities)' : ' · Movement cost ' + tt.move) + (tt.water ? ' · Water' : '') + '</p>'; }
        else { var ff = AU.FEATURES[id.slice(2)]; h = '<h3>' + ff.icon + ' ' + ff.name + '</h3><p>' + (y(ff.yields) || 'No yields') + ' · Movement cost ' + ff.move + (ff.defense ? ' · +' + ff.defense + ' defence' : '') + '</p>'; }
        break; }
      case 'resources': { var r = AU.RESOURCES[id]; if (!r) return ''; h = '<h3>' + r.icon + ' ' + r.name + ' <span class="pill">' + r.kind + '</span></h3><p>' + y(r.yields, true) + ' · Improvement: ' + link('improvements', r.improvement, AU.IMPROVEMENTS[r.improvement].name) + ' · Terrain: ' + r.terrain.join(', ') + (r.revealTech ? ' · Revealed by ' + link('techs', r.revealTech, AU.TECH_BY_ID[r.revealTech].name) : '') + '</p>' + (r.kind === 'luxury' ? '<p>Each distinct worked Luxury gives +1 Happiness in every settlement (up to 4).</p>' : r.kind === 'strategic' ? '<p><b>Needed by:</b> ' + Object.keys(AU.UNITS).filter(function (u) { return AU.UNITS[u].resource === id; }).map(function (u) { return link('units', u, AU.UNITS[u].name); }).join(', ') + '</p>' : ''); break; }
      case 'improvements': { var im = AU.IMPROVEMENTS[id]; if (!im) return ''; h = '<h3>' + im.icon + ' ' + im.name + '</h3><p>' + y(im.yields, true) + '. Built automatically when a citizen claims a matching tile.</p>'; break; }
      case 'specializations': { var sp = AU.SPECIALIZATIONS[id]; if (!sp) return ''; h = '<h3>' + sp.icon + ' ' + sp.name + '</h3><p>' + sp.desc + ' Requires population ' + sp.minPop + '. A specialized Town stops growing and sends surplus food to your nearest City.</p>'; break; }
    }
    return h;
  }

  P.render_pedia = function (app, g, data) {
    var st = app.pediaState; if (data.cat) st.cat = data.cat; if (data.id !== undefined) st.id = data.id;
    var html = '<div class="tabs">' + CATS.map(function (c) { return '<button class="small ' + (st.cat === c[0] ? 'on' : '') + '" data-action="pedia" data-cat="' + c[0] + '">' + c[1] + '</button>'; }).join('') + '</div>';
    html += '<input id="pedia-search" placeholder="Search…" value="' + (st.q || '').replace(/"/g, '') + '" style="width:100%;margin-bottom:10px">';
    if (st.cat === 'techs' || st.cat === 'civics') html += '<button class="small gold" data-action="tree" data-kind="' + (st.cat === 'techs' ? 'tech' : 'civic') + '" style="margin-bottom:10px">🌳 View the full ' + (st.cat === 'techs' ? 'technology' : 'civics') + ' tree</button>';
    html += '<div id="pedia-list"></div><div id="pedia-entry" class="pedia-entry"></div>';
    setTimeout(function () { P.renderPediaList(app); }, 0);
    return { title: 'Chibipedia', html: html };
  };
  P.renderPediaList = function (app) {
    var st = app.pediaState, list = $('pedia-list'), ent = $('pedia-entry'); if (!list) return;
    var q = (st.q || '').toLowerCase();
    var items = q ? CATS.reduce(function (acc, c) { return acc.concat(entries(c[0]).filter(function (e) { return e.name.toLowerCase().indexOf(q) >= 0; }).map(function (e) { e.cat = c[0]; return e; })); }, []) : entries(st.cat).map(function (e) { e.cat = st.cat; return e; });
    if (!st.id || (!q && !entries(st.cat).some(function (e) { return e.id === st.id; }))) st.id = items.length ? items[0].id : null;
    if (st.id && !q) st.cat = st.cat; 
    var cur = items.filter(function (e) { return e.id === st.id; })[0];
    if (!cur && items.length) { cur = items[0]; st.id = cur.id; }
    list.innerHTML = '<div class="pedia-list">' + items.slice(0, 200).map(function (e) { return '<button class="small ' + (e.id === st.id && e.cat === (cur ? cur.cat : st.cat) ? 'on' : '') + '" data-action="pedia" data-cat="' + e.cat + '" data-id="' + e.id + '">' + e.name + (e.sub ? ' <small class="stat">' + e.sub + '</small>' : '') + '</button>'; }).join('') + '</div>';
    ent.innerHTML = cur ? entry(cur.cat, cur.id) : '<p class="stat">Nothing found.</p>';
  };
  AU.Pedia = { entries: entries, entry: entry, CONCEPTS: CONCEPTS };
})(globalThis.AU = globalThis.AU || {});
