// What every technology and civic card shows: one concrete, instantly readable chibi scene each (no text on the card).
module.exports = {
  techs: {
    pottery: 'a chibi potter shaping a big clay pot on a wheel, finished painted pots around',
    animal_husbandry: 'a chibi herder with a crook next to a fluffy sheep and a cow in a wooden pen',
    mining: 'a chibi miner with a pickaxe hitting a rock wall full of sparkling ore, a cart of stones',
    hunting: 'a chibi hunter with a bow and a spear, a deer pelt and a campfire',
    fishing: 'a chibi fisherman on a small boat pulling a net full of fish',
    sailing: 'a small wooden sailboat with a big square sail on blue waves, a chibi sailor waving',
    mysticism: 'a chibi shaman in a feathered mask dancing around a fire with glowing symbols',
    irrigation: 'chibi farmers digging channels of water between green fields',
    archery: 'a chibi archer drawing a big bow at a straw target',
    writing: 'a chibi scribe writing on a clay tablet and a papyrus scroll with a reed pen',
    masonry: 'chibi masons stacking cut stone blocks into a wall with a wooden crane',
    bronze_working: 'a chibi smith pouring glowing bronze into a mould, bronze swords on a rack',
    wheel: 'a chibi carpenter proudly holding a big wooden spoked wheel next to a cart',
    celestial_navigation: 'a chibi navigator on a ship deck looking at a starry sky with a star chart',
    currency: 'a chibi merchant weighing shiny gold coins on a scale, piles of coins',
    horseback_riding: 'a chibi rider galloping on a happy horse',
    iron_working: 'a chibi blacksmith hammering a red-hot iron sword on an anvil, sparks flying',
    calendar: 'a chibi priest pointing at a big round stone calendar with sun and moon symbols',
    shipbuilding: 'chibi shipwrights building a wooden ship hull in a dock with planks and ropes',
    mathematics: 'a chibi scholar drawing triangles and numbers on a board with a compass and an abacus',
    roads: 'a paved stone road winding through hills with a chibi traveller and a milestone',
    construction: 'chibi builders raising a wooden scaffold and a stone arch with pulleys',
    engineering: 'a chibi engineer with a big lever moving a giant stone block, gears and pulleys',
    optics: 'a chibi scholar looking through a big glass lens, light rays bending',
    herbalism: 'a chibi healer grinding herbs in a mortar surrounded by plants and potion bottles',
    metallurgy: 'a chibi smith at a roaring furnace with bellows, ingots of different metals',
    military_tactics: 'a chibi commander moving tiny soldier figurines on a map table',
    apprenticeship: 'a chibi master craftsman teaching a young apprentice at a workbench',
    machinery: 'a chibi inventor beside a big wooden machine of gears, cranks and a crossbow',
    compass: 'a chibi explorer holding a big glowing magnetic compass',
    education: 'a chibi teacher at a blackboard with chibi students and open books',
    paper: 'a chibi papermaker lifting a wet sheet of paper from a vat, stacks of paper',
    stirrups: 'a chibi armoured knight standing in the stirrups of a galloping horse',
    three_field_system: 'three neat fields in different colours with a chibi farmer and a plough',
    military_engineering: 'chibi sappers building a siege tower and a catapult',
    castles: 'a cute stone castle with towers and a drawbridge on a hill',
    alchemy: 'a chibi alchemist with bubbling flasks, a glowing potion and a golden egg',
    heraldry: 'a chibi herald holding a colourful coat of arms shield with a lion, banners around',
    clockwork: 'a chibi clockmaker with a big golden mechanical clock full of gears',
    cartography: 'a chibi cartographer drawing a world map with a compass rose and sea monsters',
    mass_production: 'a row of chibi workers making identical goods on a long workbench',
    banking: 'a chibi banker at a counter with a ledger, coins and a big vault',
    gunpowder: 'a chibi soldier lighting the fuse of a small cannon, a barrel of black powder',
    printing: 'a chibi printer working a big wooden printing press, printed pages flying',
    astronomy: 'a chibi astronomer looking through a brass telescope at planets and stars',
    square_rigging: 'a tall sailing ship with many square sails, chibi sailors in the rigging',
    metal_casting: 'a chibi foundry worker pouring molten metal into a big bell mould',
    anatomy: 'a chibi doctor pointing at an anatomy chart of a friendly skeleton',
    siege_tactics: 'a chibi general beside a big bombard cannon aimed at a castle wall',
    scientific_method: 'a chibi scientist with beakers, a balance and a notebook running an experiment',
    joint_stock: 'chibi merchants shaking hands over share certificates and a model ship',
    fortification: 'a star-shaped fortress with earth walls and cannons, chibi guards',
    industrialization: 'a brick factory with tall smoking chimneys and a big steam engine',
    scientific_theory: 'a chibi professor with a chalkboard full of formulas and a glowing lightbulb idea',
    ballistics: 'a chibi artillery officer measuring the arc of a cannonball with a protractor',
    military_science: 'a chibi officer at a military academy with maps, a sabre and a globe',
    steam_power: 'a shiny steam engine with a spinning wheel, a chibi engineer shovelling coal',
    sanitation: 'chibi workers laying big pipes and a fountain of clean water',
    economics: 'a chibi economist with a rising chart, coins and a scale',
    rifling: 'a chibi gunsmith inspecting a rifle barrel, bullets on a table',
    railroad: 'a cute steam locomotive on rails crossing a bridge, puffing smoke',
    telegraph: 'a chibi operator tapping a telegraph key, poles and wires behind',
    mass_agriculture: 'a chibi farmer driving a tractor through huge golden wheat fields',
    explosives: 'a chibi miner pushing a detonator plunger, rocks blasting apart',
    refining: 'an oil refinery with tanks and pipes, a chibi worker with a wrench',
    electricity: 'a chibi inventor with a glowing lightbulb, a dynamo and lightning bolts',
    radio: 'a chibi announcer speaking into a vintage microphone next to a big radio tower',
    chemistry: 'a chibi chemist with colourful bubbling test tubes and a periodic table',
    steel: 'a chibi steelworker beside a Bessemer converter pouring glowing steel',
    replaceable_parts: 'a chibi mechanic assembling identical parts from a conveyor belt',
    flight: 'a cute biplane flying through clouds with a chibi pilot in goggles',
    ideology_tech: 'chibi crowds waving flags of different colours in a square',
    refrigeration: 'a chibi worker opening a big fridge full of food, ice crystals',
    automobile: 'a cute vintage car with a chibi driver honking a horn',
    combustion: 'a chibi mechanic tuning a shiny engine with pistons',
    electronics: 'a chibi technician with a circuit board, vacuum tubes and a soldering iron',
    advanced_ballistics: 'a chibi soldier aiming a bazooka, a missile on a ramp',
    telecommunications: 'a chibi person on a vintage phone with a satellite dish and signal waves',
    plastics: 'a chibi worker with colourful plastic toys and bottles from a moulding machine',
    computers: 'a chibi programmer at a big retro computer with reels of tape and blinking lights',
    rocketry: 'a cute rocket lifting off on a pillar of fire, a chibi scientist cheering',
    radar: 'a chibi operator at a green radar screen, a spinning radar dish',
    penicillin: 'a chibi doctor holding a petri dish and a syringe, glowing green mould',
    nuclear_fission: 'a chibi physicist next to a glowing atom model with orbiting electrons',
    combined_arms: 'a chibi tank, a chibi plane and chibi infantry advancing together',
    synthetic_materials: 'a chibi chemist with rolls of synthetic fabric and rubber tyres',
    television: 'a chibi family watching a vintage television with antenna ears',
    advanced_flight: 'a sleek jet fighter breaking the sound barrier with a chibi pilot',
    jet_engines: 'a chibi engineer beside a big jet engine with a glowing turbine',
    satellites: 'a cute satellite with solar panels orbiting a small Earth',
    nuclear_power: 'a nuclear power plant with cooling towers and a chibi worker in a hard hat',
    spaceflight: 'a chibi astronaut floating in space beside a capsule and the Earth',
    robotics: 'a chibi engineer with a friendly robot arm assembling a car',
    lasers: 'a chibi scientist firing a bright red laser beam through prisms',
    the_internet: 'a chibi person at a laptop with a glowing globe of connected nodes',
    genetics: 'a chibi geneticist beside a big glowing DNA double helix',
    composites: 'a chibi engineer holding a carbon-fibre wing panel, layered materials',
    stealth: 'a black angular stealth bomber flying at night, a chibi pilot',
    guidance_systems: 'a chibi technician with a guided missile and a targeting screen',
    nanotechnology: 'a chibi scientist looking through a microscope at tiny glowing nanobots',
    artificial_intelligence: 'a chibi scientist talking to a friendly glowing holographic robot face',
    fusion: 'a chibi physicist next to a glowing donut-shaped fusion reactor',
    quantum_computing: 'a chibi scientist beside a golden chandelier-like quantum computer',
    future_tech: 'a chibi inventor with a floating futuristic device, holograms and stars'
  },
  civics: {
    code_of_laws: 'a chibi judge holding a stone tablet of laws and a balance scale',
    craftsmanship: 'a chibi craftsman carving a wooden chair with tools in a workshop',
    foreign_trade: 'chibi traders exchanging goods from a camel caravan and a ship',
    military_tradition: 'a line of chibi warriors saluting a veteran with a scarred shield',
    state_workforce: 'chibi workers in a row carrying baskets of stone under a foreman with a plan',
    early_empire: 'a chibi king on a throne with a map of many villages and a crown',
    rituals: 'chibi villagers dancing in a circle around a totem with drums',
    oral_tradition: 'a chibi elder telling stories to children around a campfire',
    political_philosophy: 'chibi thinkers in togas debating on the steps of a temple',
    games_recreation: 'chibi athletes racing and wrestling in a small arena with cheering fans',
    drama_poetry: 'a chibi actor in a mask on a stage, a poet with a lyre',
    military_training: 'chibi recruits doing drills with wooden swords under a drill sergeant',
    recorded_history: 'a chibi historian writing in a huge book beside a stack of scrolls',
    defensive_tactics: 'chibi soldiers locking shields into a wall behind a palisade',
    mysticism_civic: 'a chibi oracle in a temple with incense smoke and a glowing crystal',
    trade_league: 'chibi merchants from different cities signing a pact over a table of goods',
    feudalism: 'a chibi lord on a horse receiving a bow from chibi peasants near a castle',
    civil_service: 'chibi clerks with brushes and scrolls sitting an exam in a hall',
    mercenaries: 'a chibi captain with a bag of gold hiring rough soldiers at a tavern',
    guilds: 'chibi artisans with a guild banner, each holding the tool of their trade',
    divine_right: 'a chibi king being crowned by a priest with a beam of light from above',
    naval_tradition: 'a chibi admiral on a ship deck with a fleet of sailing ships behind',
    exploration: 'a chibi explorer with a spyglass on a ship prow spotting new land',
    medieval_faires: 'a colourful fair with chibi jugglers, stalls and a jousting tent',
    humanism: 'a chibi scholar admiring a marble statue and a painting in a sunlit studio',
    diplomatic_service: 'chibi ambassadors in fancy clothes bowing and exchanging gifts',
    reformed_church: 'a chibi preacher nailing a paper to a church door, a crowd listening',
    mercantilism: 'a chibi treasurer guarding chests of gold and a warehouse of goods',
    enlightenment: 'a chibi philosopher with a quill and a glowing lamp of ideas in a salon',
    colonialism: 'chibi settlers stepping off a ship with flags onto a new shore',
    absolutism: 'a chibi sun king in a huge wig on a golden throne with kneeling courtiers',
    the_arts: 'chibi artists painting, sculpting and playing violin in a gallery',
    civil_engineering: 'chibi engineers with blueprints beside a bridge and a canal lock',
    nationalism: 'a chibi crowd waving one big flag together in front of a monument',
    opera_ballet: 'a chibi opera singer and a ballerina on a stage with red curtains',
    natural_history: 'a chibi naturalist with a magnifying glass, butterflies and a dinosaur skeleton',
    urbanization: 'a bustling street of tall townhouses with chibi crowds and a tram',
    scorched_earth: 'a chibi general looking at a burning field, smoke on the horizon',
    capitalism: 'a chibi businessman in a top hat with a stock ticker and factories',
    conservation: 'a chibi ranger planting a tree in a park with deer and a waterfall',
    ideology: 'three chibi speakers on podiums with red, blue and green banners',
    mass_media: 'chibi people reading newspapers around a radio and a cinema screen',
    mobilization: 'chibi citizens lining up at a recruitment desk, trucks and flags',
    suffrage: 'chibi women and men putting ballots in a box under a banner',
    totalitarianism: 'a giant statue of a leader, chibi soldiers marching in perfect rows',
    class_struggle: 'chibi workers with raised fists and a red flag in front of a factory',
    cultural_heritage: 'a chibi curator restoring an old painting in a museum',
    cold_war: 'two chibi leaders glaring across a table with a red phone and missiles behind',
    professional_sports: 'a chibi football star scoring in a huge stadium with fireworks',
    rapid_deployment: 'chibi soldiers jumping from a helicopter with parachutes',
    space_race: 'two chibi rockets racing to a cartoon moon with flags',
    environmentalism: 'chibi activists planting trees beside wind turbines and solar panels',
    globalization: 'chibi people of all nations around a globe with container ships and planes',
    social_media: 'chibi people taking selfies with phones, hearts and likes floating',
    digital_democracy: 'chibi citizens voting on tablets with a glowing holographic parliament',
    corporate_libertarianism: 'a gleaming corporate tower with a chibi CEO and drones',
    synthetic_technocracy: 'chibi scientists and a robot council around a glowing data table',
    smart_power: 'a chibi diplomat with a briefcase flanked by a soldier and a scientist',
    exodus_imperative: 'chibi colonists boarding a huge starship under a fading sun',
    cultural_hegemony: 'a chibi pop star on a giant screen with fans from every country'
  }
};
