// One bold, instantly recognisable symbol per empire for the round emblem badges.
module.exports = {
  rome: 'a golden Roman aquila eagle with spread wings above a laurel wreath',
  japan: 'a red rising sun with white rays behind a red torii gate',
  china: 'a golden coiled Chinese dragon',
  america: 'a bald eagle head in profile with a ring of white stars',
  india: 'the Ashoka chakra, a 24-spoke wheel, over a pink lotus flower',
  indonesia: 'a golden Garuda bird with spread wings',
  mongolia: 'a galloping horse with a rider drawing a bow',
  zulu: 'a tall oval Nguni cowhide shield with two crossed spears',
  persia: 'the Faravahar, a winged sun disc with a figure in the centre',
  egypt: 'a golden ankh flanked by two eyes of Horus',
  celts: 'a triskelion, three spiral arms, in Celtic knotwork',
  arabia: 'a green crescent moon with a star above a date palm',
  france: 'a golden fleur-de-lis',
  england: 'three golden lions walking, stacked, on red',
  aztec: 'an eagle perched on a prickly-pear cactus holding a snake',
  inca: 'a golden sun with a smiling face and wavy rays (Inti)',
  maya: 'a jaguar head glyph in Maya carved style',
  shawnee: 'a turtle with feathers, the Shawnee clan animal, in woodland beadwork style',
  greece: 'the owl of Athena with an olive branch',
  germany: 'a black heraldic eagle with spread wings on gold',
  russia: 'a golden double-headed eagle with a crown',
  spain: 'a red rampant lion beside a golden castle',
  ottoman: 'a white crescent moon and star on red',
  korea: 'the red and blue taegeuk yin-yang circle with four black trigrams',
  vietnam: 'a bronze Dong Son drum seen from above with a sun pattern',
  ethiopia: 'the Lion of Judah walking with a cross staff',
  mali: 'a golden lion with a Mansa crown in front of a mud-brick mosque tower',
  norway: 'a Viking longship with a red-and-white striped sail and a dragon prow',
  babylon: 'a striding lion of the Ishtar Gate on blue glazed tiles',
  polynesia: 'a carved wooden tiki face with koru spirals',
  carthage: 'the sign of Tanit, a circle over a bar and a triangle, with a crescent',
  byzantium: 'a golden Chi-Rho monogram on imperial purple',
  poland: 'a white crowned eagle with spread wings on red',
  sumer: 'Anzu, a lion-headed eagle with spread wings, in clay-tablet style',
  hittites: 'a Hittite bronze sun disc standard with antlers',
  assyria: 'a lamassu, a winged bull with a bearded human head',
  nubia: 'a steep Nubian pyramid with a bow and arrows',
  holy_roman_empire: 'the jewelled octagonal imperial crown with an orb and sceptre',
  portugal: 'a golden armillary sphere',
  netherlands: 'an orange lion holding a sword and a bundle of arrows',
  sweden: 'three golden crowns on blue',
  brazil: 'a yellow diamond around a blue globe with the Southern Cross stars',
  khmer: 'the five-towered silhouette of Angkor Wat',
  siam: 'a white elephant with a golden headdress',
  austria_hungary: 'a black double-headed eagle with two crowns on gold and red',
  scotland: 'a red rampant lion beside a purple thistle',
  kongo: 'a spotted leopard with a Kongo cross',
  mapuche: 'an eight-pointed Guñelve star over a painted kultrun drum',
  australia: 'a kangaroo with the Southern Cross stars',
  georgia: 'a red Bolnisi cross with four small crosses on white'
};
