// Merges web/i18n/parts/<lang>-*.json (English → translation objects) into web/i18n/<lang>.json and the <lang>.js the game loads.
// Usage: node tools/i18n-merge.js it   (or several codes, or none for every language that has parts)
const fs = require('fs'), path = require('path');
const dir = path.join(__dirname, '..', 'web', 'i18n'), parts = path.join(dir, 'parts');
const NAMES = { it: 'Italian', es: 'Spanish', de: 'German', fr: 'French', nl: 'Dutch', zh: 'Simplified Chinese', ru: 'Russian', bg: 'Bulgarian' };
const keys = JSON.parse(fs.readFileSync(path.join(dir, 'keys.json'), 'utf8')), keySet = new Set(keys);
let langs = process.argv.slice(2).filter(a => !a.startsWith('--'));
if (!langs.length) langs = Array.from(new Set(fs.readdirSync(parts).map(f => f.split('-')[0]).filter(l => NAMES[l])));
for (const lang of langs) {
  const file = path.join(dir, lang + '.json');
  const d = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : {};
  let added = 0, bad = 0;
  for (const f of fs.readdirSync(parts).filter(f => f.startsWith(lang + '-') && f.endsWith('.json')).sort()) {
    let obj; try { obj = JSON.parse(fs.readFileSync(path.join(parts, f), 'utf8')); } catch (e) { console.log('  invalid JSON in', f, e.message); bad++; continue; }
    for (const k in obj) { if (!keySet.has(k)) { bad++; continue; } if (typeof obj[k] !== 'string' || !obj[k].trim()) continue; if (d[k] !== obj[k]) added++; d[k] = obj[k]; }
  }
  for (const k of Object.keys(d)) if (!keySet.has(k)) delete d[k];
  const missing = keys.filter(k => !d[k]);
  fs.writeFileSync(file, JSON.stringify(d, Object.keys(d).sort(), 0).replace(/","/g, '",\n"'));
  fs.writeFileSync(path.join(dir, lang + '.js'), '// generated by tools/i18n-merge.js from ' + lang + '.json: English → ' + NAMES[lang] + '\nwindow.AU = window.AU || {}; AU.I18N_DICT = ' + JSON.stringify(d) + ';\n');
  console.log(lang + ':', Object.keys(d).length + '/' + keys.length, 'translated,', missing.length, 'missing,', added, 'updated,', bad, 'rejected keys');
  if (missing.length && process.argv.includes('--list-missing')) console.log(JSON.stringify(missing.slice(0, 400), null, 0));
}
