// Distinctive visual cues per leader so the chibi portraits look like the historical person, not a generic face.
module.exports = {
  trajan: 'Roman emperor Trajan: short cropped grey-brown hair combed forward in the Roman fashion, clean-shaven, strong square jaw, purple toga with a gold clasp and a golden laurel wreath',
  augustus: 'Roman emperor Augustus: youthful clean-shaven face, short wavy brown hair with a fringe, calm serene expression, white toga with purple stripe, oak-leaf civic crown',
  caesar: 'Julius Caesar: receding short grey hair combed forward, clean-shaven, sharp cheekbones and a hawk nose, red military cloak over a cuirass, laurel wreath',
  tokugawa: 'Tokugawa Ieyasu: shaved-pate samurai topknot, thin moustache and small goatee, round face, black lacquered kabuto helmet with golden fern crest, dark haori with the hollyhock mon',
  hojo: 'Hojo Tokimune: young samurai with a topknot, stern narrow eyes, purple and black kamakura-era armour with red lacing, a tachi sword',
  meiji: 'Emperor Meiji: short black hair parted to the side, full moustache and goatee, 19th-century black military uniform with gold epaulettes and medals',
  qin: 'Qin Shi Huang: long black beard and moustache, stern eyes, black imperial robe with red and gold dragons, flat mianguan crown with hanging bead strings',
  duke_xiao: 'Duke Xiao of Qin: Warring States ruler, thin moustache, black and gold court robe with a tall black official cap, calm calculating look',
  taizong: 'Emperor Taizong of Tang: strong-jawed emperor with a short beard, yellow imperial robe with dragon embroidery, black futou cap with wings, warm confident smile',
  wu: 'Empress Wu Zetian: elegant Tang-dynasty lady, elaborate black updo with golden phoenix hairpins, red and gold silk robe, confident regal smile',
  kublai: 'Kublai Khan: round face with a thin drooping moustache and chin beard, Mongol fur-trimmed hat with red tassel, white and gold Yuan robe',
  roosevelt: 'Theodore Roosevelt: round pince-nez glasses, bushy moustache, wide toothy grin, short brown hair, Rough Rider khaki uniform',
  lincoln: 'Abraham Lincoln: tall gaunt face, chin-strap beard without moustache, deep-set eyes, black stovepipe hat, black frock coat and bow tie',
  franklin: 'Benjamin Franklin: bald crown with long grey hair to the shoulders, small round spectacles, kindly smile, brown 18th-century coat with a fur collar',
  gandhi: 'Mahatma Gandhi: bald, round wire spectacles, white moustache, gentle smile, simple white khadi shawl',
  ashoka: 'Emperor Ashoka: dark curly hair under a golden Mauryan crown, large gold earrings, saffron and gold robes, peaceful expression, a dharma wheel pendant',
  akbar: 'Akbar the Great: Mughal emperor with a thin moustache, white jewelled turban with a heron feather, embroidered green and gold jama coat, pearl necklaces',
  gitarja: 'Queen Gitarja of Majapahit: Javanese queen with a tall golden crown, dark hair, golden jewellery, batik sarong and a shoulder sash',
  gajah: 'Gajah Mada: bald-headed Javanese general with a heavy jaw, fierce eyes, bare chest with a golden necklace, red and gold cloth',
  genghis: 'Genghis Khan: weathered face with a long thin grey beard, narrow eyes, fur-lined Mongol hat, leather and fur armour',
  mandukhai: 'Mandukhai Khatun: Mongol queen warrior, tall boqta headdress, braided black hair, blue deel robe with fur trim, holding a bow',
  shaka: 'Shaka Zulu: muscular Zulu king with a shaved head, feathered headband with a single crane feather, cowhide shield and short iklwa spear, leopard-skin cloak',
  cetshwayo: 'King Cetshwayo: heavyset Zulu king with a short beard, isicoco head-ring, leopard skin and beaded necklaces',
  cyrus: 'Cyrus the Great: long curled black beard in Persian style, tall fluted golden crown, purple and gold Persian robe',
  darius: 'Darius I: long square-cut curled beard, crenellated golden crown, purple robe with gold embroidery, a lotus flower in hand',
  cleopatra: 'Cleopatra: black bob wig with gold bands, heavy kohl eyeliner, golden vulture headdress with a cobra, white linen dress and a wide golden collar',
  ramses: 'Ramses II: striped blue and gold nemes headdress with a cobra, false pharaoh beard, golden collar, confident smile',
  hatshepsut: 'Hatshepsut: female pharaoh with the striped nemes headdress and a small false beard, kohl-lined eyes, white dress and golden collar',
  boudica: 'Boudica: wild long red hair, fierce green eyes, blue woad tattoos, golden torc necklace, checked Celtic cloak, a spear',
  vercingetorix: 'Vercingetorix: long flowing blond hair and a big drooping moustache, Gallic helmet with wings, golden torc, chainmail and a checked cloak',
  saladin: 'Saladin: dark beard, white turban with a golden band, green and gold Ayyubid robe, a curved scimitar at the belt',
  harun: 'Harun al-Rashid: Abbasid caliph in a black turban and black robe with gold trim, groomed dark beard, holding a book',
  napoleon: 'Napoleon Bonaparte: black bicorne hat worn sideways, short dark hair with a fringe, blue military coat with red cuffs and gold epaulettes, one hand tucked in the waistcoat',
  louis: 'Louis XIV: enormous curly dark wig, thin moustache, lace cravat, red-heeled shoes, blue coat with golden fleur-de-lis and ermine mantle',
  joan: 'Joan of Arc: short dark bob haircut, young determined face, shining plate armour, white banner with fleur-de-lis',
  victoria: 'Queen Victoria: small plump elderly queen with grey hair in a bun, white lace widow cap, black dress, small diamond crown, stern pout',
  elizabeth: 'Elizabeth I: pale face, red curly hair with pearls, huge white ruff collar, jewelled Tudor gown, small golden crown',
  churchill: 'Winston Churchill: bald, jowly bulldog face, big cigar, black homburg hat, bow tie, dark three-piece suit, V-for-victory gesture',
  montezuma: 'Montezuma: tall green quetzal-feather headdress, turquoise ear plugs, jade jewellery, blue and white feathered cloak',
  itzcoatl: 'Itzcoatl: Aztec ruler with a turquoise diadem, obsidian earplugs, jaguar-skin cloak, stern expression',
  pachacuti: 'Pachacuti: Inca emperor with the red fringed mascaipacha crown and feathers, large golden ear spools, geometric tunic in red, black and gold',
  huayna: 'Huayna Capac: Inca emperor with the mascaipacha fringe, golden sun breastplate, large ear spools, checkerboard tunic',
  sixsky: 'Lady Six Sky: Maya queen with an elaborate jade and quetzal-feather headdress, jade necklaces, painted face, white huipil dress',
  pakal: 'Pakal the Great: Maya king with an elongated forehead, tall jade mosaic headdress with green feathers, jade ear flares and pectoral',
  tecumseh: 'Tecumseh: Shawnee war chief with long black hair, a red cloth headband with a single feather, buckskin shirt, silver gorget and armbands',
  cornstalk: 'Chief Cornstalk: Shawnee elder with long grey hair, beaded headband with feathers, fur-trimmed robe and wampum necklace',
  pericles: 'Pericles: Greek statesman with a curly dark beard, Corinthian helmet pushed back on the head, white himation',
  leonidas: 'Leonidas: Spartan king with a thick black beard, red crested bronze helmet, red cloak, round shield with a lambda',
  alexander: 'Alexander the Great: young, clean-shaven, tousled golden-blond hair, head tilted, bronze muscle cuirass and red cloak',
  barbarossa: 'Frederick Barbarossa: big fiery red beard, golden imperial crown, red and gold robe with the black imperial eagle',
  bismarck: 'Otto von Bismarck: bald with a walrus moustache, heavy brows, spiked Prussian pickelhaube helmet, white cuirassier uniform',
  frederick: 'Frederick the Great: elderly king with a powdered white wig tied back, tricorne hat, blue Prussian coat with a red collar, holding a cane',
  peter: 'Peter the Great: very tall, dark curly hair, thin moustache, green Preobrazhensky uniform coat, holding a ship model',
  catherine: 'Catherine the Great: powdered grey rococo hair, blue sash, diamond crown, silver and gold gown with ermine',
  ivan: 'Ivan the Terrible: gaunt face with a long pointed dark beard, fur-trimmed golden Monomakh cap, jewelled brocade robe, piercing eyes',
  isabella: 'Isabella of Castile: auburn hair under a jewelled hood, golden crown, red and gold gown with the castle-and-lion arms',
  philip: 'Philip II of Spain: pale face, blond beard and moustache, black Spanish doublet with a white ruff, golden fleece chain',
  mehmed: 'Mehmed the Conqueror: hooked nose, reddish beard, large white turban, red and gold kaftan, sniffing a rose',
  suleiman: 'Suleiman the Magnificent: very tall white turban with a jewel and feather, long dark moustache, green and gold kaftan',
  sejong: 'King Sejong: kind round face with a thin beard, red dragon robe, black winged Joseon king cap, holding a Hangul scroll',
  sunsin: 'Admiral Yi Sun-sin: Joseon admiral in red and black armour with a plumed helmet, thin beard, standing before a turtle ship',
  trung: 'Trưng Trắc: Vietnamese warrior queen in a golden headdress, red and yellow armour dress, riding a war elephant',
  leloi: 'Lê Lợi: Vietnamese emperor with a black beard, golden dragon robe, black gauze cap, holding a legendary sword',
  menelik: 'Menelik II: Ethiopian emperor with a full grey beard, wide-brimmed hat wrapped in a white cloth, lion-mane cape, crown',
  zara: 'Zara Yaqob: Ethiopian emperor with a dark beard, tall golden crown with a cross, white and gold shamma robe',
  mansa: 'Mansa Musa: Malian king in a golden crown and flowing white and gold robes, holding a golden nugget and a sceptre',
  sundiata: 'Sundiata Keita: Malian lion king with a lion-mane headdress, leather armour, spear, bright patterned cloth',
  harald: 'Harald Hardrada: long blond hair and braided beard, Viking helmet with a nose guard, chainmail, blue cloak, battle axe',
  olav: 'Olav Tryggvason: red-bearded Viking king with a cross pendant, fur cloak, round shield',
  hammurabi: 'Hammurabi: Babylonian king with a long curled black beard, rounded brimmed cap, fringed robe, holding a stone law tablet',
  nebuchadnezzar: 'Nebuchadnezzar II: conical golden crown, long braided beard, blue robe with golden lions like the Ishtar Gate',
  kamehameha: 'Kamehameha: Hawaiian king with a yellow and red feathered mahiole helmet and feather cloak, powerful build',
  hotu: 'Hotu Matu\'a: Polynesian navigator chief with a feather headdress, tattooed face, bark-cloth cape, moai statue behind him',
  hannibal: 'Hannibal Barca: dark curly hair and short beard, one eye covered with a patch, Carthaginian bronze armour, war elephant behind him',
  dido: 'Queen Dido: Phoenician queen with long dark braided hair, purple Tyrian dress, golden diadem, sea behind her',
  justinian: 'Justinian I: Byzantine emperor with a jewelled golden crown with hanging pearls, purple robe with a golden tablion, halo-like gold background',
  theodora: 'Theodora: Byzantine empress with a tall jewelled crown with pearl strings, purple and gold robe, heavy pearl necklaces',
  basil: 'Basil II: stern Byzantine emperor with a short beard, golden armour, purple cloak, jewelled crown',
  casimir: 'Casimir the Great: Polish king with a curly beard, golden crown, red robe with the white eagle',
  jadwiga: 'Jadwiga: young Polish queen with long blonde hair, golden crown, white gown with a red cross',
  sobieski: 'Jan Sobieski: heavy moustache, shaved head with a Polish crest of hair, winged hussar armour, red kontusz coat',
  gilgamesh: 'Gilgamesh: enormous curled black beard and long hair, muscular hero, horned crown, Sumerian tufted kaunakes skirt',
  urnammu: 'Ur-Nammu: Sumerian king with a rounded cap, shaved face, fringed woollen robe, carrying a basket of bricks',
  suppiluliuma: 'Suppiluliuma I: Hittite great king with a conical horned crown, curled beard, long robe with a curved lituus staff',
  hattusili: 'Hattusili III: Hittite king with a pointed cap, braided beard, a winged sun disc on his robe',
  ashurbanipal: 'Ashurbanipal: Assyrian king with a tall fez-like crown, long square curled beard, fringed robe, holding a clay tablet and a lion',
  tiglath: 'Tiglath-Pileser III: Assyrian king with a conical crown, long curled beard, bronze scale armour, bow',
  amanirenas: 'Amanirenas: Kushite warrior queen, one-eyed with a scar, tall Kushite crown with feathers, golden jewellery, spear',
  piye: 'Piye: Kushite pharaoh with a skullcap crown and double uraeus cobras, dark skin, golden collar',
  charlemagne: 'Charlemagne: tall king with a long grey moustache and beard, golden imperial crown, blue mantle with golden fleur-de-lis, sword Joyeuse',
  otto: 'Otto I: Ottonian emperor with a short brown beard, jewelled octagonal imperial crown, orb and sceptre',
  charles_v: 'Charles V: prominent Habsburg jaw and lower lip, reddish beard, black doublet with the golden fleece, imperial crown',
  henry_navigator: 'Henry the Navigator: dark hair under a wide black chaperon hat, thin moustache, black robe, holding an astrolabe and a map',
  joao: 'João II: Portuguese king with shoulder-length dark hair, a small crown, red velvet doublet, holding a globe',
  william_orange: 'William of Orange: dark hair, short beard, black doublet with a white ruff, orange sash',
  dewitt: 'Johan de Witt: long curly dark hair, thin moustache, black coat with a wide white collar',
  gustavus: 'Gustavus Adolphus: blond hair, pointed beard, buff leather coat, blue sash, wide-brimmed hat with a plume',
  kristina: 'Queen Kristina: short curly brown hair, boyish look, black riding coat with a white collar, book in hand',
  pedro: 'Pedro II of Brazil: long white beard, bald crown, small spectacles, green imperial mantle with golden stars',
  vargas: 'Getúlio Vargas: short, round face, slicked dark hair, cigar, dark suit',
  jayavarman: 'Jayavarman VII: Khmer king with a serene smiling face like the Bayon towers, eyes half closed, bare chest, tall hair bun',
  suryavarman: 'Suryavarman II: Khmer king with a tall golden pointed crown, golden armbands, sampot, Angkor Wat behind him',
  ramkhamhaeng: 'Ramkhamhaeng: Thai king with a tall golden pointed crown, golden shoulder ornaments, holding a stone inscription',
  naresuan: 'Naresuan: Thai warrior king in golden armour with a pointed crown, riding a war elephant, sword',
  franz_joseph: 'Franz Joseph I: elderly emperor with white mutton-chop side whiskers and a bald head, white military tunic with red collar and medals',
  maria_theresa: 'Maria Theresa: rococo empress with powdered grey curls, small crown, blue and gold gown with lace',
  sisi: 'Empress Elisabeth: long dark braided hair wound around her head with diamond stars, slim, white gown',
  bruce: 'Robert the Bruce: Scottish king with reddish hair and beard, chainmail, golden crown over a helmet, spider on his cloak',
  james_iv: 'James IV: Scottish king with long auburn hair and beard, red doublet, thistle badge',
  nzinga: 'Nzinga Mbande: Kongo-Ndongo queen with a tall feathered headdress, beaded necklaces, leopard skin, holding a spear and an axe',
  afonso: 'Afonso I of Kongo: Kongo king in a European-style crown and cape combined with raffia cloth and a cross',
  lautaro: 'Lautaro: young Mapuche warrior with long black hair and a headband, poncho with geometric patterns, holding a club',
  galvarino: 'Galvarino: fierce Mapuche warrior with blades strapped to both forearms in place of hands, headband, poncho',
  curtin: 'John Curtin: 1940s Australian prime minister with round glasses, receding grey hair, grey suit',
  menzies: 'Robert Menzies: heavy-set, bushy eyebrows, swept-back grey hair, dark suit with a bow tie',
  tamar: 'Queen Tamar of Georgia: long dark hair under a jewelled Byzantine-style crown, red and gold robe, halo-like gold background',
  david_builder: 'David the Builder: Georgian king with a dark beard, golden crown, red robe, holding a model church'
};
