// How every unique unit looks (one line each, used by the art manifest). Ships: ship only, no people.
module.exports = {
  legion: 'a Roman legionary in lorica segmentata with a red rectangular scutum shield, gladius and a crested helmet',
  samurai: 'a Japanese samurai in lacquered o-yoroi armour with a horned kabuto helmet, holding a katana',
  crouching_tiger: 'a Chinese Ming-era soldier next to a small bronze "crouching tiger" cannon on a wooden stand',
  minuteman: 'an American colonial minuteman in a tricorn hat and brown coat with a flintlock musket',
  varu: 'an Indian war elephant with a painted trunk, a howdah and a mahout',
  jong: 'a Javanese jong, a large multi-decked wooden sailing ship with tanja sails, ship only, no people',
  keshig: 'a Mongol horse archer in a lamellar coat and fur-trimmed hat on a shaggy steppe pony',
  impi: 'a Zulu warrior with a tall cowhide shield, a short iklwa spear and a feathered headdress',
  immortal: 'a Persian Immortal in an embroidered robe and headband with a wicker shield and spear',
  maryannu: 'an Egyptian chariot archer in a two-horse chariot drawing a bow',
  gaesatae: 'a Celtic warrior with a golden torc, a long oval shield and javelins, painted body',
  mamluk: 'an Arab mamluk cavalryman with a curved sabre and a turbaned helmet on an Arabian horse',
  garde_imperiale: 'a Napoleonic imperial guard grenadier in a tall bearskin hat and blue coat with a musket',
  redcoat: 'a British redcoat infantryman in a red coat with white cross belts, a shako and a musket',
  eagle_warrior: 'an Aztec eagle warrior in an eagle-feather costume with a beaked helmet and an obsidian macuahuitl club',
  kispoko: 'a Shawnee warrior with a feathered roach headdress, painted face and a war club',
  hoplite: 'a Greek hoplite in a bronze Corinthian helmet with a large round shield and a spear',
  landsknecht: 'a German landsknecht in slashed colourful clothes and a wide feathered hat with a huge two-handed sword',
  cossack: 'a Russian cossack in a papakha fur hat with a sabre on a horse',
  tercio: 'a Spanish tercio pikeman in a morion helmet and breastplate with a very long pike',
  janissary: 'an Ottoman janissary in a tall white börk hat with a musket and a yatagan sword',
  hwacha: 'a Korean hwacha, a wooden wheeled cart launching dozens of rocket arrows, no people',
  voi_chien: 'a Vietnamese war elephant with a lacquered howdah and an archer',
  shotel: 'an Ethiopian warrior with a curved shotel sword, a round hide shield and a white robe',
  sofa: 'a Malian sofa horseman in quilted armour with a lance on a decorated horse',
  berserker: 'a Norse berserker in a bear pelt with a two-handed axe and a round painted shield',
  sabum: 'a Babylonian infantryman with a bronze helmet, spear and a fringed tunic',
  maori_warrior: 'a Maori warrior with a taiaha staff, a feather cloak and facial moko tattoos',
  quinquereme: 'a Carthaginian quinquereme warship with three banks of oars and a bronze ram, ship only, no people',
  dromon: 'a Byzantine dromon warship with lateen sails and a Greek-fire siphon at the prow, ship only, no people',
  winged_hussar: 'a Polish winged hussar in plate armour with feathered wings on his back and a lance, on a horse',
  war_cart: 'a Sumerian war cart with four solid wooden wheels pulled by onagers, with a driver and a javelin thrower',
  three_man_chariot: 'a Hittite chariot with a driver, a shield bearer and a spearman, pulled by two horses',
  assyrian_slinger: 'an Assyrian slinger in a conical helmet and scale coat whirling a sling',
  pitati: 'a Nubian archer with a long bow, a leather quiver and a feathered headband',
  genoese_crossbowman: 'a Genoese crossbowman with a tall pavise shield and a heavy crossbow',
  nau: 'a Portuguese nau carrack ship with red cross sails and a high forecastle, ship only, no people',
  sea_beggar: 'a small fast Dutch warship with orange flags and white sails, ship only, no people',
  carolean: 'a Swedish carolean soldier in a blue coat with yellow facings, tricorn hat and musket',
  minas_geraes: 'a Brazilian dreadnought battleship with big gun turrets, ship only, no people',
  domrey: 'a Khmer war elephant carrying a ballista on its back',
  wild_tiger: 'a Siamese soldier of the Wild Tiger Corps in a khaki uniform with a tiger badge and a rifle',
  kuk_field_gun: 'an Austro-Hungarian field gun with two artillerymen in pike-grey uniforms',
  highlander: 'a Scottish highlander in a kilt and bonnet with a broadsword and a targe shield',
  ngao_mbebe: 'a Kongo warrior with a large oval shield, a spear and a raffia headdress',
  malon_raider: 'a Mapuche raider on horseback with a long lance and a striped poncho',
  light_horse: 'an Australian light horseman in a slouch hat with an emu plume and a rifle, on horseback',
  monaspa: 'a Georgian knight in chainmail with a lance and a shield with a red cross'
};
